import youai from "../../../assets/youai.png"
export const tools = [
  {
    id: 1,
    name: "AI Assistant Pro",
    description: "A powerful AI assistant that helps you with daily tasks, scheduling, and reminders.",
    category: "productivity",
    subcategory: "personal-assistant",
    logo: youai,
    url: "https://example.com/ai-assistant-pro",
    tags: ["Assistant", "Productivity", "Free"],
  },
  {
    id: 2,
    name: "ResearchGPT",
    description: "AI-powered research assistant that helps you find and summarize academic papers.",
    category: "productivity",
    subcategory: "research",
    logo: youai,
    url: "https://example.com/researchgpt",
    tags: ["Research", "Academic", "Paid"],
  },
  {
    id: 3,
    name: "SpreadsheetAI",
    description: "Transform your spreadsheets with AI-powered formulas, analysis, and visualization.",
    category: "productivity",
    subcategory: "spreadsheets",
    logo: youai,
    url: "https://example.com/spreadsheetai",
    tags: ["Spreadsheets", "Data Analysis", "Freemium"],
  },
  {
    id: 4,
    name: "VideoMaster AI",
    description: "Create professional videos with AI-powered editing, enhancement, and generation.",
    category: "video",
    subcategory: "video-editing",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/videomaster-ai",
    tags: ["Video Editing", "Enhancement", "Paid"],
  },
  {
    id: 5,
    name: "TextGen Pro",
    description: "Generate high-quality content for blogs, social media, and marketing materials.",
    category: "text-generators",
    subcategory: "writing-generators",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/textgen-pro",
    tags: ["Content Generation", "Writing", "Freemium"],
  },
  {
    id: 6,
    name: "BusinessAI Suite",
    description: "All-in-one AI solution for business operations, marketing, and customer service.",
    category: "business",
    subcategory: "marketing",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/businessai-suite",
    tags: ["Business", "Marketing", "Paid"],
  },
  {
    id: 7,
    name: "ImageCreator AI",
    description: "Create stunning images from text descriptions with advanced AI technology.",
    category: "image",
    subcategory: "image-generators",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/imagecreator-ai",
    tags: ["Image Generation", "Design", "Freemium"],
  },
  {
    id: 8,
    name: "AutoFlow",
    description: "Automate your workflows with AI-powered task management and process optimization.",
    category: "automation",
    subcategory: "workflows",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/autoflow",
    tags: ["Automation", "Workflow", "Paid"],
  },
  {
    id: 9,
    name: "TranslateAI",
    description: "Translate text and documents into multiple languages with high accuracy.",
    category: "productivity",
    subcategory: "translator",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/translateai",
    tags: ["Translation", "Language", "Free"],
  },
  {
    id: 10,
    name: "PresentationGenius",
    description: "Create professional presentations with AI-generated content, design, and animations.",
    category: "productivity",
    subcategory: "presentations",
    logo: "/placeholder.svg?height=60&width=60",
    url: "https://example.com/presentationgenius",
    tags: ["Presentations", "Design", "Freemium"],
  },
]

